print('===========================================================')
print('                     EXERCICIO 10                          ')
print('===========================================================')
n1 = float(input('quantos reais você possui em sua carteira para conversão em dolares: '))
print(f'você pode comprar {n1/4.86} dolares com o que voce possui na carteira')
