print('===========================================================')
print('                     EXERCICIO 9                           ')
print('===========================================================')
n1 = int(input('digite um numero: '))
print("A tabuada desse numero é: ")
print(f'{n1}x1 = {n1*1}')
print(f' {n1}x2 = {n1*2}')
print(f'{n1}x3 = {n1*3}')
print(f'{n1}x4 = {n1*4}')
print(f'{n1}x5 = {n1*5}')
print(f'{n1}x6 = {n1*6}')
print(f'{n1}x7 = {n1*7}')
print(f'{n1}x8 = {n1*8}')
print(f'{n1}x9 = {n1*9}')
print(f'{n1}x10 = {n1*10}')
print("yessir!!!!!!")
