print('===========================================================')
print('                     EXERCICIO 4                           ')
print('===========================================================')
soma = input("escreva algo: ")
print(f"o tipo primitivo de {soma} é: ", type(soma))
print(soma, "é composto somente por letras? ", soma.isalpha())
print(f"{soma} é composto somente por numeros? ", soma.isnumeric())
print(f"{soma} é alfanumerico? ", soma.isalnum())
print(f"{soma} é composto somente por letras maiusculas? ", soma.isupper())
print(f"{soma} é composto por somente por letras minusculas?", soma.islower())
print(f"{soma} está mostravel? ", soma.isprintable())