print('===========================================================')
print('                     EXERCICIO 24                          ')
print('===========================================================')
cid = str(input('digite a cidade que você nasceu: ')).strip()
resultado = cid.lower()
print(resultado[:5]== 'santo')
